name: anytime
description: Anytime Podcast Player

version: 0.4.1+28

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  auto_size_text: ^2.1.0
  audio_service: ^0.16.2
  audio_session: ^0.0.11
  connectivity: ^0.4.8+6
  cupertino_icons: ^1.0.0
  flutter_dialogs: ^1.0.3
  flutter_downloader: ^1.5.2
  flutter_html: ^1.2.0
  flutter_launcher_icons: ^0.8.1
  flutter_spinkit: ^4.1.2+1
  get_version: ^0.2.2
  html: ^0.14.0+4
  just_audio: ^0.6.14+1
  liquid_pull_to_refresh: ^2.0.0
  logging: ^0.11.4
  mp3_info: ^0.1.4
  optimized_cached_image: ^1.0.0
  path_provider: ^1.6.27
  percent_indicator: ^2.1.9+1
  permission_handler: ^5.1.0+2
  # Use direct from GitHub until dependent also updates
  podcast_search:
    git:
      url: https://github.com/amugofjava/podcast_search
      ref: 6c4526f
  provider: ^4.3.3
  rxdart: ^0.24.1
  scrollable_positioned_list: ^0.1.9
  sembast: ^2.4.10
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  intl_translation:

dev_dependencies:
  mockito: ^4.1.4
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/anytime-logo.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/anytime-logo.png
    - assets/images/anytime-logo-s.png
    - assets/images/anytime-placeholder-logo.png

  fonts:
    - family: SpaceMonoRegular
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: SpaceMonoBold
      fonts:
        - asset: assets/fonts/SpaceMono-Bold.ttf
    - family: RobotoCondensedBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: JostRegular
      fonts:
        - asset: assets/fonts/jost/Jost-Regular.ttf
